### ISSUE TITLE
Mention BCC-to-self approach in Email article

### ISSUE THREAD

**Issue by link2xt** [KasparEtter/ef1p#4]
In the section "How to avoid submitting the same message to both the outgoing mail server and the incoming mail server?" a common approach of sending a BCC copy to self is not mentioned.

For example, Thunderbird in Account settings offers an option to "Bcc these email addresses: ". When checked, the default value is your own address.

Delta Chat offers an option to send BCC copy to self as the only option to store copies.

**Comment by KasparEtter** [comment]
Good point, I haven't thought about that there. I will add this in the coming days. Thanks for suggesting this!

**Comment by KasparEtter** [comment]
Done: https://explained-from-first-principles.com/email/#double-submission-problem
