### ISSUE TITLE
Front page language referencing nav bar items

### ISSUE THREAD

**Issue by avtraino** [KasparEtter/ef1p#9]
The ["Dark and light mode"](https://explained-from-first-principles.com/#dark-and-light-mode) section contains the following excerpt:

> "you can toggle the style by clicking on the last entry of the navigation bar"

As of 2cef1c8, the last entry is no longer the `theme-toggler`. 

Cool site!

**Comment by KasparEtter** [comment]
Thanks and great catch! 😊

**Comment by KasparEtter** [comment]
Fixed in https://github.com/KasparEtter/ef1p/commit/32c9b553c14165133a93dfc0c0fd2c28dc16ba38.
